name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install oboe
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/kmaasrud/oboe.git
        
    - name: Generate HTML with oboe
      run: oboe ./Vault -o ./out -t ./template.html -d Design/Typography

    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assets:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git checkout master -- assets/
          git add assets/.
          git commit -m "Update assets"
          git push origin gh-pages