name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install oboe
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/kmaasrud/oboe.git
        
    - name: Generate HTML with oboe
      run: oboe ./Vault -o ./out -t ./template.html -d Design/Typography

    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'Vault/Assets'
          destination-github-username: 'ChristopherKober'
          destination-repository-name: 'personal-wiki'
          target-branch: gh-pages
          user-email: ChristopherKober@users.noreply.github.com
          commit-message: See ORIGIN_COMMIT
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY